chore(classnames): upgrade classnames package to 2.3.2
lumapps/design-system pull request #1012
Opened 2023-08-23 15:49 UTC by ggougeon

# General summary

Upgrade `classnames` package to `2.3.2`

# Screenshots

StoryBook: https://13894bc0--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=300)) **⚠️ Outdated commit**

2023-08-25 06:35 UTC, juanigalan91 approved these changes

2023-08-25 06:36 UTC, juanigalan91 requested changes
Can you update the changelog md in order to show that these changes are unreleased?

2023-08-30 08:07 UTC, gcornut approved these changes

2023-08-30 12:58 UTC, gcornut commented
Test OK - no regression on generated class names (no change on automatic chromatic snapshots)

2023-08-30 13:03 UTC, merged