fix(widget-base): title widget displays scroll
lumapps/design-system pull request #1024
Opened 2023-11-06 14:43 UTC by npankov

Fix: https://lumapps.atlassian.net/browse/SUP-4003 

# General summary
Title widget displays scroll bars on Windows + Chrome

# Screenshots

2023-11-07 13:43 UTC, matmkian requested changes

2023-11-07 13:43 UTC, matmkian commented on packages/lumx-core/style-dictionary/properties/core/typography.json
> +                "line-height": { "value": "1.5" }
Line height is 1.5 by default -> just remove all typography line heights and it will inherit from 1.5 line height from the DS

2023-11-07 13:45 UTC, matmkian commented
> Personnally I would keep the line-height option for custom titles, as we used it for some client's CSS and if it disappears it would have some impact.

@SophieChristophe the variable will still be there but no default value so it inherits from 1.5 global line height. So we have to remove the default values but let define line heights if wanted.

2023-11-07 13:46 UTC, SophieChristophe commented
> > Personnally I would keep the line-height option for custom titles, as we used it for some client's CSS and if it disappears it would have some impact.
> 
> @SophieChristophe the variable will still be there but no default value so it inherits from 1.5 global line height. So we have to remove the default values but let define line heights if wanted.

That's OK for me, just want to make sure the available customizations don't disappear

2023-11-09 13:35 UTC, matmkian approved these changes

2023-11-10 09:06 UTC, gcornut requested changes
I think it's a bit risky to remove variables, if anyone uses the line height SCSS variables in their code, they will get an "undefined variable" error. 
I think the solution would be to set the line height variables to `null`. Null variables in SCSS are simply ignored, just what we want. 
But I need to update the CSS variable generation to ignore null values (not a valid value in CSS)

2023-11-10 09:11 UTC, matmkian commented
> I think it's a bit risky to remove variables, if anyone uses the line height SCSS variables in their code, they will get an "undefined variable" error. I think the solution would be to set the line height variables to `null`. Null variables in SCSS are simply ignored, just what we want. But I need to update the CSS variable generation to ignore null values (not a valid value in CSS)

+1 for null value rather than removing it

2023-11-10 13:44 UTC, gcornut approved these changes

2023-11-13 09:53 UTC, npankov commented
## Tests OK ✅ 
✅ scroll bar is not displayed on the custom title windows + chrome and other's
✅ line-height inherit from 1.5 line height from the DS

2023-11-13 11:24 UTC, gcornut commented
Rebased and fixed changelog conflict

2023-11-13 11:46 UTC, merged