feat(thumbnail): add thumbnail badge
lumapps/design-system pull request #624
Opened 2021-02-03 15:43 UTC by gcornut

2021-02-03 15:56 UTC, FlorentDinet commented
👍

2021-02-03 16:01 UTC, pidupuis approved these changes

2021-02-05 14:01 UTC, matmkian requested changes

2021-02-05 14:01 UTC, matmkian commented on packages/lumx-core/src/scss/components/thumbnail/_index.scss
> +@each $key, $size in $lumx-sizes {
Can we remove that part? Not sure it's needed? It's going to be weird with light badges -> it has box shadow

2021-02-05 14:25 UTC, matmkian approved these changes

2021-02-05 14:57 UTC, merged