chore(doc): add more doc on thumbnail loading and error state
lumapps/design-system pull request #789
Opened 2022-03-02 17:09 UTC by gcornut

# General summary

Add more doc on thumbnail loading and error state

2022-03-03 08:56 UTC, FlorentDinet commented on packages/site-demo/content/product/components/thumbnail/index.mdx
> +## Loading skeleton
"Loading ~skeleton~state"

Skeleton is the component that make possible l[oading states](https://design.lumapps.com/product/patterns/loading-state/)

2022-03-03 09:09 UTC, FlorentDinet commented on packages/site-demo/content/product/components/thumbnail/index.mdx
> +While loading the image, the thumbnail displays a loading skeleton but only if the thumbnail has sufficient
We always use the plural for components.
And never write "you"

I'd re-write this part like that :

Thumbnails display a loading state while loading image. To display loading state, thumbnails require defined size.

For example:

2022-03-03 09:10 UTC, FlorentDinet commented on packages/site-demo/content/product/components/thumbnail/index.mdx
> +  the thumbnail will scale down if the given `width` and `height` are bigger than allowed space
"Thumbnails will scale down..."

2022-03-03 09:14 UTC, FlorentDinet commented on packages/site-demo/content/product/components/thumbnail/index.mdx
> +You can customize this state using the `fallback` prop to change the icon or even replace with a custom React node.
Error state can be customize using the `fallback` prop to change the icon or even replace with a custom React node.

2022-03-03 09:15 UTC, FlorentDinet requested changes
I've made suggestion to doc text.

We had [guidelines](https://www.notion.so/e1212cfc50ae4ae38f5a5fea3946d0bb) for writing doc but not accessible anymore, I'm trying to recover them

2022-03-11 16:12 UTC, FlorentDinet approved these changes
All good 👏

2022-03-11 16:27 UTC, juanigalan91 approved these changes

2022-03-14 08:52 UTC, merged