fix(button): fix color props allowing string not in colorpalette
lumapps/design-system pull request #929
Opened 2022-12-05 10:44 UTC by Fafnor

[CF-407](https://lumapps.atlassian.net/browse/CF-407)

# General summary
Change the type of the color prop of the DS components to accept only ColorPalette values (instead of accepting string too)

# Screenshots

2022-12-05 13:30 UTC, carlo-lumapps approved these changes

2022-12-05 13:46 UTC, gcornut requested changes

2022-12-05 13:46 UTC, gcornut commented on packages/lumx-react/src/components/index.ts
> -export type Color = ColorPalette | string;
I think we should keep the `Color` type as an alias to the `ColorPalette` so that users do not have to replace it from their import.

2022-12-06 09:45 UTC, gcornut commented
Rebased & improved changelog message

2022-12-06 10:36 UTC, gcornut approved these changes

2022-12-06 10:39 UTC, gcornut commented
On hold to test type error inpact in lumapps-web 
(also v3.0.7 will soon be merged to master and this PR will need to be rebased and changelog will need to be updated to make sure the change in this PR appear in the right section)

2022-12-14 10:32 UTC, gcornut commented
Test OK ✔️

2022-12-14 10:38 UTC, merged