fix(uploader): improve a11y & doc ARCH-59
lumapps/design-system pull request #986
Opened 2023-06-08 15:11 UTC by gcornut

- fix(uploader): use true button to improve accessibility
- feat(uploader): add native file input handler
- docs(uploader): add accessibility concerns section

Use a true `<button>` button by default to improve accessibility. 
Use `<input type=file>` and `<label>` if `fileInputProps` is provided to handle a native file picker and to support dropping a file onto the uploader.

2023-06-14 12:22 UTC, Mcourt approved these changes

2023-06-14 12:26 UTC, Mcourt requested changes
Wait actually, I'm no too sure about this.
If we see "Uploaders" as buttons that opens the native file picker, I'm not so sure they should be "buttons".
There might be some places where it should be a "label" with a file input linked to it.
Like we could see on these resources:
[Medium - Accessible File Uploads
](https://medium.com/@christophergoodwin.me/accessible-file-uploads-9ecacac17276)
[Accessibility.com - A styled accessible file upload
](https://accessabilly.com/a-styled-accessible-file-upload/)

If this is not the intended use, we could probably add more context in the doc section?
We should at least be able to use it like this somehow.

2023-06-14 14:38 UTC, Mcourt approved these changes
After some further research, I have found some resource that seem to show that this solution can be acceptable.
Approving and it can always be enhanced later.

2023-06-15 07:32 UTC, gcornut commented
Deployed StoryBook: https://5fbfb1d508c0520021560f10-ybfgjlvwgt.chromatic.com/?path=/story/lumx-components-alert-dialog-alertdialog--default-kind

2023-06-20 12:06 UTC, merged